apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-app
  name: go-app
  namespace: exam-49
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-app
  type: ClusterIP
