apiVersion: v1
kind: Pod
metadata:
  labels:
    author: Sodiqmirzo
    project: practice
  name: nginx2
  namespace: exam-49
spec:
  containers:
  - image: nginx
    name: nginx2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
